# Generated by Django 3.1.8 on 2021-05-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware_revision', models.CharField(blank=True, max_length=100, null=True)),
                ('software_revision', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_version', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.BinaryField(blank=True, editable=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_update_started', models.DateTimeField(verbose_name='Timestamp')),
                ('fw_update_success', models.BooleanField()),
                ('device_firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware_revision', models.CharField(blank=True, max_length=100, null=True)),
                ('software_revision', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.device')),
                ('firmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.firmware', verbose_name='Flashed Firmware')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.firmware'),
        ),
    ]
