# Generated by Django 3.1.8 on 2021-05-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210505_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='hw_compability',
            field=models.CharField(default='v5', max_length=100),
            preserve_default=False,
        ),
    ]
