# Generated by Django 3.1.8 on 2021-05-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_firmware_hw_compability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firmware',
            unique_together={('fw_version', 'hw_compability')},
        ),
    ]
